### ISSUE TITLE
Any chance to also support the .net framework? 

### ISSUE THREAD

**Issue by Sicos1977** [UnDotNet/HtmlToText#2]
Any chance to also support the .net framework?  I'm stuck on .net 4.8.2 (because of webforms) and you are now only targeting .net 6

Also keep up the good work. In the past I have written something myself that uses HtmlAgilityPack but I now am hitting some downsides on my own sollution because HTML (in e-mails in my case) are getting more complex so it is sometimes hard to get something readable out of it so that I can find data inside the e-mail with regular expressions :-)

**Comment by Sicos1977** [comment]
I made a pull request to add support for .net framework 4.8. It are just some minor tweaks that are needed.

Just decide if you want to use it or not. No problems if you dont want to add it because I than just keep my fork.

**Comment by JohnCampionJr** [comment]
Sure, I'll get this merged; thanks for the PR!
